#!/bin/bash
LOG=/var/log/Xvnc-dynamic

function main(){
	local BASH_SOURCE=$(readlink -nf "${BASH_SOURCE}")

	# restore user xstartup
	# loop through backups restoring the first diff
	# remove any matching files as accidents
	if find "${BASH_SOURCE}".user* &> /dev/null; then
		local xstartup=""
		while read xstartup; do
			if diff "${xstartup}" "${BASH_SOURCE}"; then
				rm -f "${xstartup}"
			else
				mv -f "${xstartup}" "${BASH_SOURCE}"
				break
			fi
		done < <(ls -1t "${BASH_SOURCE}".user*)
	else
	      rm -f "${BASH_SOURCE}"
	fi

	# get desktop session paths
	local GSESSION="$(which gnome-session		2>/dev/null)"
	local STARTKDE="$(which startkde		2>/dev/null)"
	local      TWM="$(which twm			2>/dev/null)"
	local    ICEWM="$(which icewm-session		2>/dev/null)"
	local  FLUXBOX="$(which fluxbox			2>/dev/null)"
	local    XFCE4="$(which xfce4-session		2>/dev/null)"
	local      KDE="$(which startkde		2>/dev/null)"

	local SSHAGENT="$(which ssh-agent		2>/dev/null)"
	local CKLAUNCH="$(which ck-launch-session	2>/dev/null)"

	# is Ubuntu
	if cat /etc/lsb-release | grep -q -i ubuntu; then
		local GSESSION="$(which gnome-session-fallback	2>/dev/null)"

	# is Red Hat | CentOS
	elif [ -f /etc/redhat-release ]; then
		local CKLAUNCH="$(which ck-xinit-session	2>/dev/null)"

	fi

	# setup Ubuntu RedHat differences

	# simply send some data to the LOG 
	local vncPID=`gvncPID`
	local sockets=(`gSockets`)
	local rfbport=${sockets[0]#*:}
	local desktop=$(gxstartup)

	echo XCLIENTS :: Starting Desktop                  >> "${LOG}"
	echo XCLIENTS :: \ vncPID :: ${vncPID}             >> "${LOG}"
	echo XCLIENTS ::  rfbport :: ${rfbport}            >> "${LOG}"
	echo XCLIENTS ::  desktop :: ${desktop}            >> "${LOG}"
	echo --------------------------------------------- >> "${LOG}"
	#env                                                >> "${LOG}"
	#echo --------------------------------------------- >> "${LOG}"
	echo                                               >> "${LOG}"
	#desktop=twm
	case ${desktop} in
		gnome)		exec "${CKLAUNCH}" "${SSHAGENT}" "${GSESSION}";;

		xfce4)		exec "${CKLAUNCH}" "${SSHAGENT}" "${XFCE4}";;

		kde)		exec "${CKLAUNCH}" "${SSHAGENT}" "${KDE}";;

		ice)		[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources
				xsetroot -solid grey
				exec "${CKLAUNCH}" "${SSHAGENT}" "${ICEWM}";;

		fluxbox)	[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources
				xsetroot -solid grey
				exec "${CKLAUNCH}" "${SSHAGENT}" "${FLUXBOX}";;

		twm)		[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources
				xsetroot -solid grey
				xterm -geometry 80x24+10+10 -ls -title "$VNCDESKTOP Desktop" &
				exec "${CKLAUNCH}" "${SSHAGENT}" "${TWM}";;
	esac
}
function gvncPID(){
	cat "${HOME}/.vnc/"*"${DISPLAY}.pid"
}
function gSockets(){
	local ocket='\([0-9\.\*]\+:[0-9\*]\+\)'	# sed socket filter
	local p='[[:space:]]\+'			# sed white space key
	local vncPID=`gvncPID`
	ss -atlnp |\
	sed -n "/,${vncPID},/s/.*$p$ocket$p$ocket$p.*/\1 \2/p"
}
function gxstartup(){
	local sockets=(`gSockets`)
	local rfbport=${sockets[0]#*:}
	cat   "${HOME}/.vnc/xstartup.${rfbport}"
	rm -f "${HOME}/.vnc/xstartup.${rfbport}"
}
main "$@"

