#!/bin/bash

function main(){

	#echo "${majors}"
	shopt -q extglob && local EXTGLOB=true || shopt -s extglob
		ls -1 "${BASH_SRCDIR}/Xvnc-dynamic.sh".v\\\+\([0-9]\)
	${EXTGLOB:-false} || shopt -u extglob
	#GET_VERSION
	




}
function GET_VERSION(){
	local major=""
	shopt -q extglob && local EXTGLOB=true || shopt -s extglob
	for major in ${majors}; do
		ls -1 "${BASH_SRCDIR}/${major}".v\+\([0-9]\)           2>/dev/null
		ls -1 "${BASH_SRCDIR}/REVISIONS/${major}".v\+\([0-9]\) 2>/dev/null
	done
# | sed 's/.*\.v//'


	${EXTGLOB:-false} || shopt -u extglob


}


function canonicalpath(){
	if [ -d $1 ]; then
		pushd $1 > /dev/null 2>&1
		echo $PWD
	elif [ -f $1 ]; then
		pushd $(dirname $1) > /dev/null 2>&1
		echo $PWD/$(basename $1)
	else
		echo "Invalid path $1"
	fi
	popd > /dev/null 2>&1
}
# GLOBAL vars; fully qualified script paths and names
BASH_SRCFQFN=$(canonicalpath "${BASH_SOURCE}")
BASH_SRCNAME=$(basename "${BASH_SRCFQFN}")
BASH_SRCDIR=$(dirname "${BASH_SRCFQFN}")

# Projects major scripts
read -d $'' majors <<-EOE
	Xvnc-dynamic.sh
	x11vnc.sh
	xstartup
EOE

main "$@"
