#!/bin/bash
# https://github.com/zfsonlinux/pkg-zfs/wiki/HOWTO-install-Ubuntu-to-a-Native-ZFS-Root-Filesystem

root_password="1qaz\@WSX"
boot_grub="sda3"
bios_grub="sda1"

function main(){
	# Step 5: System Configuration
	#      5.5 Base system setup
	locale-gen en_US.UTF-8
	apt-get update	
	#apt-get -y install ubuntu-minimal python-software-properties software-properties-common
	apt-get -y install ubuntu-minimal software-properties-common
	#      5.6 Install ZFS
	apt-add-repository --yes ppa:zfs-native/stable
	apt-add-repository --yes ppa:zfs-native/grub
	apt-get update
	apt-get -y install --no-install-recommends linux-image-generic linux-headers-generic
	apt-get -y install ubuntu-zfs
	local grub=$(get_disk_by_id ${boot_grub})
	echo grub-pc grub-pc/install_devices select ${grub} | debconf-set-selections
	apt-get -y install grub2-common grub-pc
	apt-get -y install zfs-initramfs
	apt-get -y dist-upgrade
	#      5.7 Setup root password (be sure special characters are escaped)
	usermod -p $(perl -e "print crypt(\"${root_password}\",\"$(date '+%s')\")") root

	# Step 6: GRUB Instalation
	#      6.1 Verify that ZFS root filesystem is recognized by GRUB
	grub-probe /
	#          And that ZFS modules for GRUB are installed
	ls /boot/grub/zfs*
	#          Note that after Ubuntu 13, these are now in /boot/grub/i386-pc/zfs*
	ls /boot/grub/i386-pc/zfs*
	#      6.2 Refresh the initrd files
	update-initramfs -c -k all
	#      6.3 Update the boot configuration file
	update-grub
	#      6.4 Install the boot loader to the MBR like this
	grub-install /dev/sda

	# Step 7: System tweaks before reboot
	#      7.1 modify grub; disable quiet and splash
	cat <<-SED | sed -i -f <(cat) /etc/default/grub
		/GRUB_TERMINAL/{  s/^[#[:space:]]*// }
		/GRUB_INIT_TUNE/{ s/^[#[:space:]]*// }
		/GRUB_CMDLINE_LINUX_DEFAULT/{
			s/^/#/
			a\GRUB_CMDLINE_LINUX_DEFAULT=""
		}
	SED
	#      7.2 update grub
	update-grub
	#      7.3 install debconf-tools
	apt-get -y install debconf debconf-tools
	#      7.4 block grub and kernel from upgrades
	cat <<-SELECTIONS | awk '{print $0" hold"}' | dpkg --set-selections
		linux-image-generic
		linux-headers-generic
		grub-common
		grub-gfxpayload-lists
		grub-pc
		grub-pc-bin
		grub2-common
	SELECTIONS
		#linux-firmware
		#linux-firmware-nonfree

	# DONE
	count_down 10
}
function get_disk_by_id(){
	local dev=$1
	local id
	for id in $(ls -1 /dev/disk/by-id/* | grep \/scsi); do
		ls -l ${id} | grep -q "\/${dev}$" && echo ${id}
	done
}
function count_down(){
	count=$1
	while [ $count -ge 0 ]
	do
		sleep .5
		echo -n $count.
		count=$(( count - 1 ))
	done
	echo	
}




main "$@"
