#!/bin/bash

while read line; do
	#echo $line
	#line=${line// /\"\ \"}
	line=${line// /\"\ \"}
	while read file; do
		echo $file
	done < <(eval echo ${line})  
		


done < <(sed test.sh -e '/^function includes/,/^}/p;d' | sed '1d;$d')
