#!/bin/bash

while read line; do
	line=${line// /\"\ \"}
	while read file; do
		if [ -f "${file}" ]; then
			echo HOT :: ${file} 
		else
			echo COLD :: ${file}
		fi


	done < <(eval find "${line}" -type f -maxdepth 1 2> /dev/null)  
		


done < <(sed test.sh -e '/^function includes/,/^}/p;d' | sed '1d;$d')
