#!/bin/sh
#!/bin/dash

              IP=$(echo ${url} | cut -d/ -f3)
            USER=$(wget -q -O - ${url} | awk '/username/{print $NF}')
      FIRST_USER=$(wget -q -O - ${url} | awk '/username/{print $NF}')
            HTTP=${url%/*}
            SEED=${url##*/}
APT_CACHE_SERVER=${IP}
APT_CACHE_SERVER=$(wget -O - ${HTTP}/APT_CACHE_SERVER_ADDRESS)

chroot_mount(){
	local ROOT=$1
	mount --bind /dev  ${ROOT}/dev
	mount --bind /sys  ${ROOT}/sys
	mount --bind /proc ${ROOT}/proc
}
chroot_umount(){
	local ROOT=$1
	umount ${ROOT}/dev
	umount ${ROOT}/sys
	umount ${ROOT}/proc
}
chroot_enable_dns(){
	local ROOT=$1
	echo nameserver ${IP} > ${ROOT}/etc/resolv.conf
}
chroot_enable_apt_cache_proxy(){
	local ROOT=$1
	cat << PROXY  > ${ROOT}/etc/apt/apt.conf.d/01proxy
Acquire::http::Timeout "2";
Acquire::http::Proxy "http://${APT_CACHE_SERVER}:3142";
Acquire::http::Proxy::download.oracle.com "DIRECT";
Acquire::http::Proxy::virtualbox.org "DIRECT";
PROXY
}
chroot_apt_get(){
	local ROOT=$1
	shift
	chroot_mount ${ROOT}
	#chroot /root /usr/bin/apt-get update
	chroot ${ROOT} /usr/bin/apt-get $@
	chroot_umount ${ROOT}
}
chroot_add_apt_repo(){
	local ROOT=$1
	shift
	chroot_mount ${ROOT}
	chroot ${ROOT} /usr/bin/add-apt-repository $@
	chroot ${ROOT} /usr/bin/apt-get update
	chroot_umount ${ROOT}
}
chroot_profile_d(){
	local ROOT=$1
	shift
	local FILE=$1
	shift
	echo "$@" >> ${ROOT}/etc/profile.d/${FILE}
}
wget_tgz(){
	local url=$1
	local dir=$2
	local dsc=$(basename ${dir})
	chroot /root /bin/bash << BASH			\
			1>> ${LOGS}_wget-${dsc}.log	\
			2>> ${LOGS}_wget-${dsc}.log
	mkdir ${dir}
	/usr/bin/wget -O - ${url} |\
	/bin/tar -xz -C ${dir}
BASH
}
count_down(){
	local message="$(echo "$*" | sed 's/[0-9]\+//')"
	local count="$(echo "$*" | sed 's/[^0-9]*\([0-9]\+\).*/\1/')"
	local count=${count:-10}
	while [ $count -ge 0 ]
	do
		sleep .5
		echo -n $count.
		count=$(( count - 1 ))
	done
	echo $message
}
interactive(){
	local tty_num=$1
	shift
	tty_dev="/dev/tty$tty_num"
	exec $* < $tty_dev > $tty_dev 2> $tty_dev
}

